require:
  - rubocop-rake
  - rubocop-rspec

AllCops:
  NewCops: enable

Naming/FileName:
  Exclude:
    - 'lib/rubocop-notarize.rb'

RSpec/ExampleLength:
  Enabled: false

Style/Documentation:
  Enabled: false
