plugins:
  - rubocop-rake
  - rubocop-rspec

AllCops:
  NewCops: enable

Metrics/ClassLength:
  Max: 500

Metrics/CyclomaticComplexity:
  Enabled: false
  Max: 12

Metrics/MethodLength:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false
  Max: 12

Naming/FileName:
  Exclude:
    - 'lib/rubocop-notarize.rb'

RSpec/ExampleLength:
  Enabled: false

Style/Documentation:
  Enabled: false
