plugins:
  - rubocop-rake
  - rubocop-rspec

AllCops:
  NewCops: enable

Metrics/AbcSize:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Naming/FileName:
  Exclude:
    - 'lib/rubocop-notarize.rb'

RSpec/ExampleLength:
  Enabled: false

Style/Documentation:
  Enabled: false
