Performance/DisableReload:
  Description: 'Disallow users to call .reload on an ActiveRecord object'
  Enabled: pending
  VersionAdded: '0.93'

Style/DisableProgrammaticEnumValue:
  Description: 'Disallow users to create enums with an each_value statement'
  Enabled: pending
  VersionAdded: '0.93'
