Performance/DisableReload:
  Description: 'Disallow users to call .reload on an ActiveRecord object'
  Enabled: true
  VersionAdded: '0.1.5'

Performance/RequireFileOpenBlock:
  Description: 'Enforce opening files with a block to ensure the file gets closed.'
  Enabled: true
  VersionAdded: '0.1.5'

Security/DisableChdir:
  Description: 'Disallow users to call chdir with a block'
  Enabled: true
  VersionAdded: '0.1.7'

Sidekiq/RequireSidekiqTestingInlineBlock:
  Description: 'Prevent Sidekiq Testing settings from leaking into other specs'
  Enabled: true
  VersionAdded: '0.1.6'

Style/DisableProgrammaticEnumValue:
  Description: 'Disallow users to create enums with an each_value statement'
  Enabled: true
  VersionAdded: '0.1.5'

Style/GraphCamelize:
  Description: 'Do not use the GraphQL camelize option as we always want the default value (true).'
  Enabled: true
  VersionAdded: '0.1.5'

Performance/RequireFrozenStringLiteral:
  Description: 'Require # frozen_string_literal: true in any file that creates a string literal'
  Enabled: false
  VersionAdded: '0.1.8'
