Performance/DisableReload:
  Description: 'Disallow users to call .reload on an ActiveRecord object'
  Enabled: pending
  VersionAdded: '0.93'

Performance/RequireFileOpenBlock:
  Description: 'Enforce opening files with a block to ensure the file gets closed.'
  Enabled: pending
  VersionAdded: '1.31.2'

Style/DisableProgrammaticEnumValue:
  Description: 'Disallow users to create enums with an each_value statement'
  Enabled: pending
  VersionAdded: '0.93'

Swagger/SpecValidation:
  Description: 'Validates swagger spec for external endpoints'
  Enabled: false
  VersionAdded: '1.31.2' # Bump when actually released

Layout/LineLength:
  Description: 'Enforce maximum line length'
  Enabled: true
  Max: 1180
